@startuml
actor User as "User"

rectangle Database

rectangle "Population Application" {
package "Countries" {
    usecase UC01 as "View all countries in the world by population"

    usecase UC02 as "View all countries in a continent by population"

    usecase UC03 as "View all countries in a region by population"

    usecase UC04 as "View top N countries in the world by population"

    usecase UC05 as "View top N countries in a continent by population"

    usecase UC06 as "View top N countries in a region by population"
    }

    usecase UC07 as "View all cities in the world by population"

    usecase UC08 as "View all cities in a continent by population"

    usecase UC09 as "View all cities in a region by population"

    usecase UC10 as "View all cities in a country by population"

    usecase UC11 as "View all cities in a district by population"

    usecase UC12 as "View top N populated cities in the world by population"

    usecase UC13 as "View top N populated cities in a continent by population"

    usecase UC14 as "View top N populated cities in a region by population"

    usecase UC15 as "View top N populated cities in a country by population"

    usecase UC16 as "View top N populated cities in a district by population"

    usecase UC17 as "View all capital cities in the world by population"

    usecase UC18 as "View all capital cities in a continent by population"

    usecase UC19 as "View all capital cities in a region by population "

    usecase UC20 as "View top N populated capital cities in the world by population"

    usecase UC21 as "View top N populated capital cities in a continent by population"

    usecase UC22 as "View top N populated capital cities in a region by population"

    usecase UC23 as "View population living in and outside cities in each continent"

    usecase UC24 as "View population living in and outside cities in each region"

    usecase UC25 as "View population living in and outside cities in each country"

    usecase UC26 as "View population of the world"

    usecase UC27 as "View population of a continent"

    usecase UC28 as "View population of a region"

    usecase UC29 as "View population of a country"

    usecase UC30 as "View population of a district"

    usecase UC31 as "View population of a city"

    usecase UC32 as "View the number and percentage of people that speak specific languages"

    usecase UC33 as "Input Validation"

    usecase UC34 as "Generate Report"

    usecase UC35 as "Data Retrieval"


    User --> (UC01)
    User --> UC02
    User --> UC03
    User --> UC04
    User --> UC05
    User --> UC06
    User --> UC07
    User --> UC08
    User --> UC09
    User --> UC10
    User --> UC11
    User --> UC12
    User --> UC13
    User --> UC14
    User --> UC15
    User --> UC16
    User --> UC17
    User --> UC18
    User --> UC19
    User --> UC20
    User --> UC21
    User --> UC22
    User --> UC23
    User --> UC24
    User --> UC25
    User --> UC26
    User --> UC27
    User --> UC28
    User --> UC29
    User --> UC30
    User --> UC31
    User --> UC32

    UC01 ..> UC34 : include
    UC02 ..> UC34 : include
    UC03 ..> UC34 : include
    UC04 ..> UC34 : include
    UC05 ..> UC34 : include
    UC06 ..> UC34 : include
    UC07 ..> UC34 : include
    UC08 ..> UC34 : include
    UC09 ..> UC34 : include
    UC10 ..> UC34 : include
    UC11 ..> UC34 : include
    UC12 ..> UC34 : include
    UC13 ..> UC34 : include
    UC14 ..> UC34 : include
    UC15 ..> UC34 : include
    UC16 ..> UC34 : include
    UC17 ..> UC34 : include
    UC18 ..> UC34 : include
    UC19 ..> UC34 : include
    UC20 ..> UC34 : include
    UC21 ..> UC34 : include
    UC22 ..> UC34 : include
    UC23 ..> UC34 : include
    UC24 ..> UC34 : include
    UC25 ..> UC34 : include
    UC26 ..> UC34 : include
    UC27 ..> UC34 : include
    UC28 ..> UC34 : include
    UC29 ..> UC34 : include
    UC30 ..> UC34 : include
    UC31 ..> UC34 : include
    UC32 ..> UC34 : include
    UC34 ..> UC35 : include

    UC35 -- Database


}
@enduml