@startuml
actor User as "User"

rectangle Database

rectangle "Population Application" {
    usecase UC01 as "View all countries in the world by population"

    usecase UC02 as "View all countries in a continent by population"

    usecase UC03 as "View all countries in a region by population"

    usecase UC04 as "View top N countries in the world by population"

    usecase UC05 as "View top N countries in a continent by population"

    usecase UC06 as "View top N countries in a region by population"

    usecase UC07 as "View all cities in the world by population"

    usecase UC08 as "View all cities in a continent by population"

    usecase UC09 as "View all cities in a region by population"

    usecase UC10 as "View all cities in a country by population"

    usecase UC11 as "View all cities in a district by population"

    usecase UC12 as "View top N populated cities in the world by population"

    usecase UC13 as "View top N populated cities in a continent by population"

    usecase UC14 as "View top N populated cities in a region by population"

    usecase UC15 as "View top N populated cities in a country by population"

    usecase UC16 as "View top N populated cities in a district by population"

    usecase UC17 as "View all capital cities in the world by population"

    usecase UC18 as "View all capital cities in a continent by population"

    usecase UC19 as "View all capital cities in a region by population "

    usecase UC20 as "View top N populated capital cities in the world by population"

    usecase UC21 as "View top N populated capital cities in a continent by population"

    usecase UC22 as "View top N populated capital cities in a region by population"

    usecase UC23 as "View population living in and outside cities in each continent"

    usecase UC24 as "View population living in and outside cities in each region"

    usecase UC25 as "View population living in and outside cities in each country"

    usecase UC26 as "View population of the world"

    usecase UC27 as "View population of a continent"

    usecase UC28 as "View population of a region"

    usecase UC29 as "View population of a country"

    usecase UC30 as "View population of a district"

    usecase UC31 as "View population of a city"

    usecase UC32 as "View the number and percentage of people that speak specific languages"

    usecase UC33 as "Input Validation"

    usecase UC34 as "Generate Report"

    usecase UC35 as "Data Retrieval"


    User ---> (UC01)
    User ---> UC02
    User ---> UC03
    User ---> UC04
    User ---> UC05
    User ---> UC06
    User ---> UC07
    User ---> UC08
    User ---> UC09
    User ---> UC10
    User ---> UC11
    User ---> UC12
    User ---> UC13
    User ---> UC14
    User ---> UC15
    User ---> UC16
    User ---> UC17
    User ---> UC18
    User ---> UC19
    User ---> UC20
    User ---> UC21
    User ---> UC22
    User ---> UC23
    User ---> UC24
    User ---> UC25
    User ---> UC26
    User ---> UC27
    User ---> UC28
    User ---> UC29
    User ---> UC30
    User ---> UC31
    User ---> UC32

    UC01 ..> UC33 : <<includes>>
    UC02 ..> UC33 : <<includes>>
    UC03 ..> UC33 : <<includes>>
    UC04 ..> UC33 : <<includes>>
    UC05 ..> UC33 : <<includes>>
    UC06 ..> UC33 : <<includes>>
    UC07 ..> UC33 : <<includes>>
    UC08 ..> UC33 : <<includes>>
    UC09 ..> UC33 : <<includes>>
    UC10 ..> UC33 : <<includes>>
    UC11 ..> UC33 : <<includes>>
    UC12 ..> UC33 : <<includes>>
    UC13 ..> UC33 : <<includes>>
    UC14 ..> UC33 : <<includes>>
    UC15 ..> UC33 : <<includes>>
    UC16 ..> UC33 : <<includes>>
    UC17 ..> UC33 : <<includes>>
    UC18 ..> UC33 : <<includes>>
    UC19 ..> UC33 : <<includes>>
    UC20 ..> UC33 : <<includes>>
    UC21 ..> UC33 : <<includes>>
    UC22 ..> UC33 : <<includes>>
    UC23 ..> UC33 : <<includes>>
    UC24 ..> UC33 : <<includes>>
    UC25 ..> UC33 : <<includes>>
    UC26 ..> UC33 : <<includes>>
    UC27 ..> UC33 : <<includes>>
    UC28 ..> UC33 : <<includes>>
    UC29 ..> UC33 : <<includes>>
    UC30 ..> UC33 : <<includes>>
    UC31 ..> UC33 : <<includes>>
    UC32 ..> UC33 : <<includes>>
    UC33 ..> UC34 : <<includes>>
    UC34 ..> UC35 : <<includes>>

    UC35 -- Database


}
@enduml